---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tara-deployment
  labels:
    app: tara
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tara
  template:
    metadata:
      labels:
        app: tara
    spec:
      containers:
      - name: tara-api
        image: itselavia/tara:VERSION
        imagePullPolicy: Always
        ports:
        - containerPort: 9000

---

apiVersion: v1
kind: Service
metadata:
  name: tara-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:240377662125:certificate/8f248951-e102-4171-be48-0b9e20c2519d
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app: tara
  ports:
    - port: 443
      targetPort: 9000
  type: LoadBalancer
